apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: order-service
  namespace: pets
spec:
  host: order-service
  subsets:
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3